[project]
name = "physarum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "imageio>=2.37.2",
    "matplotlib>=3.10.7",
    "neurovolume>= 0.1.0a5",
    "numpy>=1.26.4",
    "scipy>=1.16.3",
]
